"""Generate a standalone MSSQL dump with literal observation rows.

Output contains 40,320 rainfall rows and 10,080 water-level rows. The joined
station-hour view therefore returns exactly 10,080 rows. All data is synthetic.
"""

from datetime import datetime, timedelta
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "mssql" / "thaiwater_literal_10080.sql"
START = datetime(2026, 7, 21)
STATIONS = 120
HOURS = 84
BATCH = 500


def sql_dt(value: datetime) -> str:
    return value.strftime("%Y-%m-%dT%H:%M:%S")


def batches(handle, table: str, columns: str, rows):
    pending = []
    for row in rows:
        pending.append(row)
        if len(pending) == BATCH:
            handle.write(f"INSERT {table} ({columns}) VALUES\n")
            handle.write(",\n".join(pending) + ";\n")
            pending.clear()
    if pending:
        handle.write(f"INSERT {table} ({columns}) VALUES\n")
        handle.write(",\n".join(pending) + ";\n")


def station_rows():
    provinces = ["10", "20", "30", "40", "50", "60", "70", "80", "90", "95", "96", "99"]
    agencies = ["HII", "RID", "DWR", "TMD"]
    for station_id in range(1, STATIONS + 1):
        yield (
            f"({station_id},'TW{station_id:03d}',N'สถานีสาธิต {station_id:03d}',"
            f"'{((station_id - 1) % 6) + 1:02d}','{provinces[(station_id - 1) % 12]}',"
            f"'{agencies[(station_id - 1) % 4]}',"
            f"{6 + ((station_id * 83) % 1400) / 100:.6f},"
            f"{98 + ((station_id * 47) % 700) / 100:.6f},'MSL1915')"
        )


def rule_rows():
    for station_id in range(1, STATIONS + 1):
        riverbed = 4 + (station_id % 20) * 0.1
        bank = 8 + (station_id % 20) * 0.1
        yield f"({station_id},'{sql_dt(START)}',NULL,{riverbed:.3f},{bank:.3f},'THAIWATER-PUBLIC-CRITERIA-LAB-1')"


def rainfall_rows():
    row_id = 1
    for hour in range(HOURS):
        for quarter in range(4):
            observed = START + timedelta(hours=hour, minutes=quarter * 15)
            for station_id in range(1, STATIONS + 1):
                n = row_id - 1
                if n % 997 == 0:
                    value, quality = "NULL", "M"
                else:
                    value = f"{((station_id * 7 + n) % 180) / 10:.2f}" if n % 29 in (0, 1, 2, 3) else "0.00"
                    quality = "S" if n % 389 == 0 else ("P" if n % 17 == 0 else "V")
                received = observed + timedelta(minutes=2 + n % 8)
                yield f"({row_id},{station_id},'{sql_dt(observed)}',{value},'{quality}','{sql_dt(received)}')"
                row_id += 1


def level_rows():
    row_id = 1
    for hour in range(HOURS):
        observed = START + timedelta(hours=hour)
        for station_id in range(1, STATIONS + 1):
            n = row_id - 1
            if n % 1301 == 0:
                level, discharge, quality = "NULL", "NULL", "M"
            else:
                level = f"{6.5 + (station_id % 20) * 0.1 + (hour % 48) * 0.035:.3f}"
                discharge = f"{20 + ((station_id * 13 + n) % 2500) / 10:.2f}"
                quality = "S" if n % 503 == 0 else ("P" if n % 19 == 0 else "V")
            datum = "LOCAL" if n % 4093 == 0 else "MSL1915"
            received = observed + timedelta(minutes=4 + n % 12)
            yield f"({row_id},{station_id},'{sql_dt(observed)}',{level},{discharge},'{datum}','{quality}','{sql_dt(received)}')"
            row_id += 1


HEADER = r"""/* Standalone literal ThaiWater-aligned training dataset.
   Every observation below is an explicit VALUES row, not generated by SQL.
   All data is synthetic and must not be represented as real ThaiWater data. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
IF DB_ID(N'ThaiWaterLiteral') IS NULL CREATE DATABASE ThaiWaterLiteral;
GO
USE ThaiWaterLiteral;
GO
DROP VIEW IF EXISTS dbo.vw_hourly_situation;
DROP TABLE IF EXISTS dbo.water_level_hourly;
DROP TABLE IF EXISTS dbo.rainfall_15min;
DROP TABLE IF EXISTS dbo.station_rule;
DROP TABLE IF EXISTS dbo.station;
DROP TABLE IF EXISTS dbo.quality_flag;
DROP TABLE IF EXISTS dbo.agency;
DROP TABLE IF EXISTS dbo.province;
DROP TABLE IF EXISTS dbo.basin;
GO
CREATE TABLE dbo.agency(agency_code varchar(10) PRIMARY KEY,agency_name_th nvarchar(200) NOT NULL);
CREATE TABLE dbo.basin(basin_code char(2) PRIMARY KEY,basin_name_th nvarchar(100) NOT NULL);
CREATE TABLE dbo.province(province_code char(2) PRIMARY KEY,province_name_th nvarchar(100) NOT NULL);
CREATE TABLE dbo.quality_flag(quality_code char(1) PRIMARY KEY,quality_name_th nvarchar(100) NOT NULL,usable_for_report bit NOT NULL);
CREATE TABLE dbo.station(station_id int PRIMARY KEY,station_code varchar(20) UNIQUE NOT NULL,station_name_th nvarchar(200) NOT NULL,basin_code char(2) REFERENCES dbo.basin,province_code char(2) REFERENCES dbo.province,agency_code varchar(10) REFERENCES dbo.agency,latitude decimal(9,6) NOT NULL,longitude decimal(9,6) NOT NULL,vertical_datum varchar(20) NOT NULL);
CREATE TABLE dbo.station_rule(station_id int REFERENCES dbo.station,effective_from datetime2(0),effective_to datetime2(0) NULL,riverbed_level_m_msl decimal(7,3),bank_level_m_msl decimal(7,3),rule_version varchar(40),PRIMARY KEY(station_id,effective_from));
CREATE TABLE dbo.rainfall_15min(rainfall_id bigint PRIMARY KEY,station_id int REFERENCES dbo.station,observed_at datetime2(0),rainfall_mm decimal(8,2) NULL,quality_code char(1) REFERENCES dbo.quality_flag,received_at datetime2(0),UNIQUE(station_id,observed_at));
CREATE TABLE dbo.water_level_hourly(water_level_id bigint PRIMARY KEY,station_id int REFERENCES dbo.station,observed_at datetime2(0),water_level_m_msl decimal(7,3) NULL,discharge_cms decimal(10,2) NULL,vertical_datum varchar(20),quality_code char(1) REFERENCES dbo.quality_flag,received_at datetime2(0),UNIQUE(station_id,observed_at));
GO
INSERT dbo.agency VALUES ('HII',N'สสน. (ข้อมูลสังเคราะห์)'),('RID',N'กรมชลประทาน (ข้อมูลสังเคราะห์)'),('DWR',N'กรมทรัพยากรน้ำ (ข้อมูลสังเคราะห์)'),('TMD',N'กรมอุตุนิยมวิทยา (ข้อมูลสังเคราะห์)');
INSERT dbo.basin VALUES ('01',N'ลุ่มน้ำสาธิต 01'),('02',N'ลุ่มน้ำสาธิต 02'),('03',N'ลุ่มน้ำสาธิต 03'),('04',N'ลุ่มน้ำสาธิต 04'),('05',N'ลุ่มน้ำสาธิต 05'),('06',N'ลุ่มน้ำสาธิต 06');
INSERT dbo.province VALUES ('10',N'จังหวัดสาธิต 10'),('20',N'จังหวัดสาธิต 20'),('30',N'จังหวัดสาธิต 30'),('40',N'จังหวัดสาธิต 40'),('50',N'จังหวัดสาธิต 50'),('60',N'จังหวัดสาธิต 60'),('70',N'จังหวัดสาธิต 70'),('80',N'จังหวัดสาธิต 80'),('90',N'จังหวัดสาธิต 90'),('95',N'จังหวัดสาธิต 95'),('96',N'จังหวัดสาธิต 96'),('99',N'จังหวัดสาธิต 99');
INSERT dbo.quality_flag VALUES ('V',N'ผ่านการตรวจสอบ',1),('P',N'ข้อมูลเบื้องต้น',1),('S',N'น่าสงสัย',0),('M',N'ไม่มีข้อมูล',0);
"""

VIEW = r"""
GO
CREATE VIEW dbo.vw_hourly_situation AS
WITH rain AS (
 SELECT r.station_id,DATEADD(hour,DATEDIFF(hour,0,r.observed_at),0) report_hour,
  SUM(CASE WHEN q.usable_for_report=1 THEN r.rainfall_mm END) rainfall_1h_mm,
  COUNT_BIG(*) reading_count,
  SUM(CASE WHEN q.usable_for_report=1 AND r.rainfall_mm IS NOT NULL THEN 1 ELSE 0 END) usable_count
 FROM dbo.rainfall_15min r JOIN dbo.quality_flag q ON q.quality_code=r.quality_code
 GROUP BY r.station_id,DATEADD(hour,DATEDIFF(hour,0,r.observed_at),0)
)
SELECT wl.observed_at report_hour,s.station_code,s.station_name_th,b.basin_name_th,
 p.province_name_th,a.agency_name_th,rain.rainfall_1h_mm,wl.water_level_m_msl,
 wl.discharge_cms,
 CAST(100.0*(wl.water_level_m_msl-sr.riverbed_level_m_msl)/NULLIF(sr.bank_level_m_msl-sr.riverbed_level_m_msl,0) AS decimal(8,2)) channel_capacity_percent,
 CASE WHEN q.usable_for_report=0 THEN 'NO_DATA' WHEN wl.vertical_datum<>s.vertical_datum THEN 'DATUM_MISMATCH'
  WHEN wl.water_level_m_msl>sr.bank_level_m_msl THEN 'OVER_BANK'
  WHEN 100.0*(wl.water_level_m_msl-sr.riverbed_level_m_msl)/NULLIF(sr.bank_level_m_msl-sr.riverbed_level_m_msl,0)>70 THEN 'HIGH'
  WHEN 100.0*(wl.water_level_m_msl-sr.riverbed_level_m_msl)/NULLIF(sr.bank_level_m_msl-sr.riverbed_level_m_msl,0)>30 THEN 'NORMAL'
  WHEN 100.0*(wl.water_level_m_msl-sr.riverbed_level_m_msl)/NULLIF(sr.bank_level_m_msl-sr.riverbed_level_m_msl,0)>10 THEN 'LOW' ELSE 'CRITICAL_LOW' END water_situation,
 CONVERT(bit,CASE WHEN rain.reading_count=4 AND rain.usable_count=4 AND q.usable_for_report=1 AND wl.vertical_datum=s.vertical_datum THEN 1 ELSE 0 END) is_complete
FROM dbo.water_level_hourly wl JOIN dbo.station s ON s.station_id=wl.station_id
JOIN dbo.basin b ON b.basin_code=s.basin_code JOIN dbo.province p ON p.province_code=s.province_code
JOIN dbo.agency a ON a.agency_code=s.agency_code JOIN dbo.quality_flag q ON q.quality_code=wl.quality_code
JOIN dbo.station_rule sr ON sr.station_id=wl.station_id AND wl.observed_at>=sr.effective_from
LEFT JOIN rain ON rain.station_id=wl.station_id AND rain.report_hour=wl.observed_at;
GO
SELECT 'rainfall literal rows' item,COUNT_BIG(*) row_count FROM dbo.rainfall_15min
UNION ALL SELECT 'water-level literal rows',COUNT_BIG(*) FROM dbo.water_level_hourly
UNION ALL SELECT 'joined report rows',COUNT_BIG(*) FROM dbo.vw_hourly_situation;
GO
"""


def main():
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(HEADER)
        batches(handle, "dbo.station", "station_id,station_code,station_name_th,basin_code,province_code,agency_code,latitude,longitude,vertical_datum", station_rows())
        batches(handle, "dbo.station_rule", "station_id,effective_from,effective_to,riverbed_level_m_msl,bank_level_m_msl,rule_version", rule_rows())
        batches(handle, "dbo.rainfall_15min", "rainfall_id,station_id,observed_at,rainfall_mm,quality_code,received_at", rainfall_rows())
        batches(handle, "dbo.water_level_hourly", "water_level_id,station_id,observed_at,water_level_m_msl,discharge_cms,vertical_datum,quality_code,received_at", level_rows())
        handle.write(VIEW)
    print(f"generated {OUTPUT}")


if __name__ == "__main__":
    main()
